# Week #4 - Numpy library for Python
### During this week, you will learn Numpy in Python.  Why is Numpy important?  It allows you to deal with complex mathematics. Before we can use any Numpy functions, we need to call the function in a library call.  After importing Numpy we can access all the functions.


### Topics You will learn
 - Arrays
 - arange
 - random integers
 - Uniform
 - random real numbers
 - normal random numbers
 - Maxtrix
 - shape/reshape matrix
 - Arithmetics of arrays
 - Adding arrays
 - Array methods
 - array indexing and Slicing

# Call Numpy library
Before using Nuumpy data types you must call the Numpy library.  The way to access Numpy library.  When ever you refer to numpy use np.

```
import numpy as np
```
### Run the code.

In [2]:
import numpy as np

# Why NumPy? (The Business Case)
### In Excel, if you want to multiply a column of prices by a column of quantities, you drag a formula down. In standard Python, you would need a "for loop." NumPy allows Vectorization, which lets us perform math on entire arrays at once—just like a single formula in an Excel cell applied to a whole range.

### Key Concept: NumPy arrays are homogeneous (all data must be the same type, usually numbers), making them much faster than standard Python lists.

### Creating Your First Arrays
#### Students should practice moving from standard Python lists to NumPy.

```
import numpy as np

# **1D Array (like a single row or column in Excel) - A "Vector"**  one row and three columns
prices = np.array([19.99, 25.50, 15.00])

# **2D Array (like a full spreadsheet) - A "Matrix"**   three rows and three columns
# Rows = Products, Columns = [Price, Cost, Inventory]
data = np.array([
    [19.99, 10.00, 50],
    [25.50, 12.00, 30],
    [15.00, 5.00, 100]
])
```
### Run the code.

In [3]:
import numpy as np

# 1D Array (like a single row or column in Excel) - A "Vector",  one row and three columns.  1 x 3 elements
prices = np.array([19.99, 25.50, 15.00])

# 2D Array (like a full spreadsheet) - A "Matrix",   three rows and three columns.  3x3 = 9 elements
# Rows = Products, Columns = [Price, Cost, Inventory]

data = np.array([
    [19.99, 10.00, 50],
    [25.50, 12.00, 30],
    [15.00, 5.00, 100]
])

# 3. Business Math: Vectorization & Broadcasting
### This is where the precalculus background shines. Instead of manual calculation, we use element-wise operations.  <br>

### Scenario: You want to apply a 10% tax to all prices. <br> 
Formula: $TaxedPrice = Price \times 1.10$
```
taxed_prices = prices * 1.10  # This is "Broadcasting" a single number across an array
```


In [4]:
taxed_prices = np.round(prices * 1.10, 2)  # This is "Broadcasting" a single number across an array
taxed_prices

array([21.99, 28.05, 16.5 ])

# Slicing and Filtering
Business data is often messy. We use slicing to extract specific values like "Price", "Cost", or "Inventory".

**Indexing: data[0, 0]**<br>
Gets the price of the first item.

**Slicing column: data[: , i]**<br>
The index i equals the column you want to access; in this case, the entire Cost column.  The first column index, 0, corresponds to the price.  The second column index, 1, corresponds to the cost.  The third column, which equals 2, is the inventory.  **1st column data[ : , 0]**.

**Slicing: data[j : k ]**<br>
The index j equals the row you want to access, in this case, the entire row.  The first row has index 0.  The second index k determine where you want to stop gathering rows. jth row stopping at k-1 rows  **1st row data[0 : 1]**

**Boolean Masking: data[: , 2] < 40** <br>
Finding all products with low inventory below 40. <br>**low_stock = data[data[:, 2] < 40]** 

```
cost = data[:, 1]
profit = prices - cost

prices  # displays prices
# in another code cell
taxed_prices  # prices with taxes
```


In [5]:
data

array([[ 19.99,  10.  ,  50.  ],
       [ 25.5 ,  12.  ,  30.  ],
       [ 15.  ,   5.  , 100.  ]])

In [6]:
data[:, 0] # 1st column

array([19.99, 25.5 , 15.  ])

In [7]:
data[:, 1]  # 2nd column

array([10., 12.,  5.])

In [8]:
data[:, 2]  # 3rd column

array([ 50.,  30., 100.])

In [9]:
data[0 :1 ]

array([[19.99, 10.  , 50.  ]])

In [10]:
cost = data[:, 1]
profit = prices - cost

profit  # displays prices

array([ 9.99, 13.5 , 10.  ])

In [11]:
# in another code cell
taxed_prices  # prices with taxes

array([21.99, 28.05, 16.5 ])

In [12]:
data[:, 0]  # first row

array([19.99, 25.5 , 15.  ])

In [13]:
# get inventory column
data[: , 2]


array([ 50.,  30., 100.])

In [14]:
low_stock = data[data[:, 2] < 40]
low_stock

array([[25.5, 12. , 30. ]])

In [15]:
data[0:1]  # First row

array([[19.99, 10.  , 50.  ]])

In [16]:
data[1: 2]  # Second row

array([[25.5, 12. , 30. ]])

In [17]:
data[2:3]  # Third row

array([[ 15.,   5., 100.]])

# Determine the size or shape of an Array

The size of the array is the number of elements in the array.  The shape of the array is the number of rows and columns.
```
print("Number of elements: ", data.size)   # number of elements
print("Number of rows and columns: ", data.shape)  # number of rows and columns
```


In [18]:
print("Number of elements: ", data.size)   # number of elements
print("Number of rows and columns: ", data.shape)  # number of rows and columns

Number of elements:  9
Number of rows and columns:  (3, 3)


# arange()
arange is similar to the range function in Python.  You can create an array of values from start, to end + 1.
```
A1 = np.arange(11)
A2 = np.arange(5, 11)
```

In [19]:
A1 = np.arange(11)
A1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
A2 = np.arange(5, 11)
A2

array([ 5,  6,  7,  8,  9, 10])

# Random Numbers
You may want to generate random numbers from 0 to 1.

```
np.random.rand()
```

In [21]:
np.random.rand()

0.7721858404185206

# Random Numbers (rows and columns)
You may want to generate random numbers between 0 and 1 that fits into a matrix of (row, column)
```
np.random.rand(3, 5) # (rows, columns)
```

In [22]:
np.random.rand(3, 5)

array([[0.78230044, 0.15936537, 0.75670781, 0.13986464, 0.41862274],
       [0.77370413, 0.14621842, 0.79408099, 0.65693145, 0.1359516 ],
       [0.46679811, 0.2504599 , 0.31776964, 0.3627163 , 0.24984173]])

# Random Numbers - Integers (rows, columns)
You may want to generate integers between integers, either as one value or a matrix of values.
```
np.random.randint(1, 101) # random number between 1 and 100
np.random.randint(1, 101, (5,3))
```

In [23]:
np.random.randint(1, 101)

81

In [24]:
np.random.randint(1, 101, (5,3))

array([[ 2,  5, 34],
       [99, 81, 30],
       [42, 26, 42],
       [38, 25, 71],
       [80, 94,  7]])

# Random Numbers - Normal
The normal distribution is very important in Statistics, so you can generate random numbers from a Normal distribution.
```
# the random number from a Normal distribution  mean = 75 and std = 5
np.random.normal(75, 5)

In [64]:
np.random.normal(75, 5)

71.75441865151274

## Create an array of 20 random numbers

In [25]:
np.random.normal(75, 5, 20)

array([71.74987094, 79.535881  , 66.38884906, 88.20921743, 73.33491471,
       73.67136221, 81.03897908, 69.28643125, 74.80165922, 84.04709149,
       76.31320632, 79.77141491, 80.41542998, 76.99331766, 76.82806331,
       85.11423222, 71.03106865, 67.20083467, 65.18661527, 74.46157173])

In [26]:
np.random.normal(75, 5, (4, 5))

array([[75.68703018, 79.49779723, 84.59712637, 80.46414059, 81.91491251],
       [74.07527895, 82.26393765, 68.34817223, 68.5026092 , 80.25786461],
       [80.52062166, 73.31084327, 82.50836547, 71.71402597, 79.59509851],
       [71.82038963, 77.58931088, 74.75889465, 77.55244333, 70.64781434]])

# Converting a list to an Array
You can use a tuple to assign the mean and standard deviation.  Use a list comprehension to create a list and convert the list to an array.
```
mean, std = (75, 1.5)
l3 = [np.random.normal(mean, std) for x in np.arange(25)]
L3 = np.array(l3)  # convert the list to an array
L3
```

In [27]:
mean, std = (75, 1.5)
l3 = [np.random.normal(mean, std) for x in np.arange(25)]
L3 = np.array(l3)
L3

array([72.89271243, 75.00417128, 72.67928451, 75.30088716, 74.64623654,
       73.17728844, 75.17691524, 76.13680472, 78.20879196, 75.65365604,
       75.58267502, 73.08887002, 73.1580717 , 74.46275156, 74.89197936,
       74.16847313, 73.71644571, 73.2996342 , 73.85865251, 75.36260625,
       75.56270683, 77.27008512, 74.10329658, 74.2353334 , 76.16429606])

# Arithmetic with NumPy Arrays
You can perform arithmetic operations with an array.  You can do all the order of operations (parentheses, raise to a power, multiplication, division, addition, or subtraction).
```
import numpy as np
A = np.array([31, 32, 33, 34, 35, 36, 37, 38, 39])
B = np.array([41, 42, 43, 44, 45, 46, 47, 48, 49])
A ** 3
A * 4
A / 3
A + 7
A - 6
(A + B) ** 2 + 3
A + 3 * B
2 * A - 4 * B
```

In [28]:
import numpy as np
A = np.array([31, 32, 33, 34, 35, 36, 37, 38, 39])
B = np.array([41, 42, 43, 44, 45, 46, 47, 48, 49])
A ** 3

array([29791, 32768, 35937, 39304, 42875, 46656, 50653, 54872, 59319])

In [29]:
A * 4

array([124, 128, 132, 136, 140, 144, 148, 152, 156])

In [30]:
A + 7

array([38, 39, 40, 41, 42, 43, 44, 45, 46])

In [31]:
A - 6

array([25, 26, 27, 28, 29, 30, 31, 32, 33])

In [32]:
(A + B) ** 2 + 3

array([5187, 5479, 5779, 6087, 6403, 6727, 7059, 7399, 7747])

In [33]:
A + 3 * B

array([154, 158, 162, 166, 170, 174, 178, 182, 186])

In [34]:
2 * A - 4 * B

array([-102, -104, -106, -108, -110, -112, -114, -116, -118])

In [35]:
G = np.array([11, 12, 13, 14, 15, 16, 17, 18, 19])
A * G

array([341, 384, 429, 476, 525, 576, 629, 684, 741])

In [36]:
A - G

array([20, 20, 20, 20, 20, 20, 20, 20, 20])

In [37]:
A/G

array([2.81818182, 2.66666667, 2.53846154, 2.42857143, 2.33333333,
       2.25      , 2.17647059, 2.11111111, 2.05263158])

In [38]:
(A + 3*G) ** 2

array([4096, 4624, 5184, 5776, 6400, 7056, 7744, 8464, 9216])

# Numpy Statistical Methods 
### Statistical methods that the numpy array uses (vectors)
 - max()
 - argmax()
 - min()
 - argmin()
 - mean()
 - median()
 - std()
 - var()
 - sum()
 - count




In [39]:
K = np.random.normal(65, 2.5, (20,1))

In [40]:
K.mean().item()

64.9708449731896

In [41]:
# maximum value
L3.max().item()

78.20879196312814

In [42]:
# index of maximum value
L3.argmax().item()

8

In [43]:
# minimum of array
L3.min().item()

72.67928451313175

In [44]:
L3.argmin().item()

2

In [45]:
L3.mean().item()

74.71210503079199

In [46]:
L3.std().item()

1.355036394569028

In [47]:
np.percentile(L3, 25).item()

73.71644570994538

In [48]:
np.percentile(L3, 75).item()

75.56270683225053

In [49]:
np.percentile(L3, 10).item()

73.11655069443736

# axis 
Axises is a variable that determines whether you are applying the method to rows (axis = 1) or columns (axis = 0).

```
X = np.arange(0, 15)
X = X.reshape(3, 5)
X.mean(axis = 0)
X.sum(axis = 0)
X.mean(axis = 1)
X.sum(axis = 1)
```


In [50]:
X = np.arange(0, 15)
X = X.reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [51]:
Y = X.sum(axis = 1)
Y

array([10, 35, 60])

In [52]:
row_1_total = Y.item(0)
row_1_total

10

In [53]:
nm = X.sum(axis = 1).item(0)
nm

10

In [54]:
X.mean(axis = 0)  # average of columns

array([5., 6., 7., 8., 9.])

In [55]:
X.mean(axis = 1)  # average of rows

array([ 2.,  7., 12.])

In [56]:
X.std(axis = 0) # standard deviation of columns

array([4.0824829, 4.0824829, 4.0824829, 4.0824829, 4.0824829])

In [57]:
X.std(axis = 1) # standard deviation of rows

array([1.41421356, 1.41421356, 1.41421356])

In [58]:
np.percentile(X, [25, 75],  axis=1)

array([[ 1.,  6., 11.],
       [ 3.,  8., 13.]])

In [59]:
(X > 4).any()  # Are there any values in X greater than 4

np.True_

In [60]:
(X > -1).all()  # Are all the values in X greater than 4

np.True_

In [61]:
L4 = np.sort(L3)
L4

array([72.67928451, 72.89271243, 73.08887002, 73.1580717 , 73.17728844,
       73.2996342 , 73.71644571, 73.85865251, 74.10329658, 74.16847313,
       74.2353334 , 74.46275156, 74.64623654, 74.89197936, 75.00417128,
       75.17691524, 75.30088716, 75.36260625, 75.56270683, 75.58267502,
       75.65365604, 76.13680472, 76.16429606, 77.27008512, 78.20879196])

# Conditional Logic
To create a new array based on the condition.
```
np.where(L4 > L4.mean(), 'higher', 'lower')
```

In [62]:
np.where(L4 > L4.mean(), 'higher', 'lower')

array(['lower', 'lower', 'lower', 'lower', 'lower', 'lower', 'lower',
       'lower', 'lower', 'lower', 'lower', 'lower', 'lower', 'higher',
       'higher', 'higher', 'higher', 'higher', 'higher', 'higher',
       'higher', 'higher', 'higher', 'higher', 'higher'], dtype='<U6')

In [63]:
w1 = L4.mean() - 1 * L4.std()
w2 = L4.mean() - 2 * L4.std()
w3 = L4.mean() + 1 * L4.std()
w4 = L4.mean() + 2 * L4.std()
np.where(L4 < w2, "2 std below", (np.where(L4 < w1, "1 std below", (np.where(L4 > w4, "1 std above", "2 std above")))))

array(['1 std below', '1 std below', '1 std below', '1 std below',
       '1 std below', '1 std below', '2 std above', '2 std above',
       '2 std above', '2 std above', '2 std above', '2 std above',
       '2 std above', '2 std above', '2 std above', '2 std above',
       '2 std above', '2 std above', '2 std above', '2 std above',
       '2 std above', '2 std above', '2 std above', '2 std above',
       '1 std above'], dtype='<U11')